# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb7ff0b3e723e0b47cbc883d9a1d00e17f0cb19fb0ed139667c4da869590121c224f033e7d692d595b7b9789858455515b699553ed71abf80e0e82c694c50ec7

test:
  secret_key_base: 819afae76dade28a9f1c3d605792e68ae5570d7bbde4c87885150c094112152e9ac097faf12d0f8fe70ba28e742badb404bc0f9462ba20a5d455de842edb4710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
